Repository ev-br/mc_lib, pull requests merged in 2021-12, with the labels that each got.

#22 Ising cluster update code
  examples/Cluster_update_examples.ipynb
  examples/cy_ising_cluster.pyx
  examples/exact_ising.pyx
  examples/setup_exact_ising.py
  examples/setup_ising_cluster.py
Labels: enhancement, needs-work

#51 WIP: random: Poisson generator w/mc_lib
  .github/workflows/dev_ubuntu_macos.yml
  .github/workflows/pip_ubuntu_macos.yml
  examples/README.md
  examples/cy_poisson.pyx
  examples/meson.build
Labels: enhancement

#55 BLD: build examples
  examples/meson.build
  examples/setup.py
  examples/setup_exact_ising.py
  examples/setup_ising_cluster.py
Labels: maintenance, build issues
